### ISSUE TITLE
Attribute error when using `mkdocs.config`

### ISSUE THREAD

**Issue by AnjoMan** [mkdocs/mkdocs#2578]
I maintain an `mkdocs` plugin that uses the built-in config types, and after upgrading to mkdocs 1.2.2 i get an attribute error when accessing `config_options` to build my plugin. I'm guessing this stuff has been relocated, or an import was dropped? Anyways, it looks like a breaking API change to me.

```
>>> import mkdocs.config
>>> mkdocs.config.config_options
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mkdocs.config' has no attribute 'config_options'
>>> mkdocs.__version__
'1.2.2'
```

**Comment by oprypin** [comment]
```bash
git bisect start
git bisect bad
git bisect good HEAD~200
git bisect run python3 -c 'import mkdocs.config; mkdocs.config.config_options'
```

> 21b3d1d431f8a9bef0450c21ee5dc60c8242c8cd is the first bad commit

---

Umm so you've been relying on the fact that `mkdocs.config` happened to import `mkdocs.config.defaults` which happens to import `mkdocs.config.config_options` (and that's all *without* reexporting those names in any way at all), but Python has a global import registry, so one of the side effects of the latter was `mkdocs.config.config_options = __import__('mkdocs.config.config_options')`.

I think it's not feasible at all to track side effects to such an extent, so for MkDocs this doesn't appear actionable in general.

---

To avoid such problems, of course you should import what you use. If you're using module `mkdocs.config.config_options`, then import that.

But you probably realize all of this, only wanted to help with your report. So, thanks for the report anyway.
