### ISSUE TITLE
Issue with running makdocs and mkdocs-material theme

### ISSUE THREAD

**Issue by stegmai** [mkdocs/mkdocs#1349]
Hi all,

i am running in trouble since my last reinstall of my system (mac). I am using mkdocs together with [mkdocs-material](https://github.com/squidfunk/mkdocs-material) for quiet a while. Currently, i get really strange errors, like the following:

`
ERROR   -  Error building page index.md 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/Library/Python/2.7/site-packages/mkdocs/commands/serve.py", line 117, in serve
    config = builder()
  File "/Library/Python/2.7/site-packages/mkdocs/commands/serve.py", line 112, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/Library/Python/2.7/site-packages/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/Library/Python/2.7/site-packages/mkdocs/commands/build.py", line 242, in build_pages
    _build_page(page, config, site_navigation, env)
  File "/Library/Python/2.7/site-packages/mkdocs/commands/build.py", line 158, in _build_page
    output_content = template.render(context)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/florian.stegmaier/Documents/workspace/audit-expert/audit-expert-api/specification/material/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/florian.stegmaier/Documents/workspace/audit-expert/audit-expert-api/specification/material/base.html", line 1, in top-level template code
    {% import "partials/language.html" as lang with context %}
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 1073, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 1152, in __init__
    body_stream = list(template.root_render_func(context))
  File "/Users/florian.stegmaier/Documents/workspace/audit-expert/audit-expert-api/specification/material/partials/language.html", line 1, in top-level template code
    {% import "partials/language/" + config.theme.language + ".html" as lang %}
jinja2.exceptions.UndefinedError: 'mkdocs.theme.Theme object' has no attribute 'language'
`

At first i thought, that there have been issues with installed versions of mkdocs and the theme, but i am not able to run the demo example of the themes master branch. Does anybody have an idea what the issue could be? 

`
Python 2.7.10
pip 9.0.1 from /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)
mkdocs, version 0.17.1
`

**Comment by waylan** [comment]
Last I knew, the material theme had not yet been updated to work with MkDocs version 0.17. Although, that could have changed in the last few weeks. I would suggest checking with that project for more information.

**Comment by martinbira** [comment]
When using MkDocs 0.17.1 and the material theme, the material theme must be 2.x. Also, if you have overwritten any partials, this may initiate the errors. See https://github.com/squidfunk/mkdocs-material/issues/516

**Comment by facelessuser** [comment]
Material has been updated to use latest Mkdocs. And it works fine.

**Comment by waylan** [comment]
I'm closing this as a downstream issue.
